server:
  port: 8080  # 您的应用程序将在此端口上运行
  address: 0.0.0.0
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 2592000


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/picture
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL的JDBC驱动类名
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    connect-timeout: 10000
    password: 123456
  session:
    store-type: redis
    # session 30天过期
    timeout: 2592000

logging:
  level:
    root: INFO  # 设置日志级别为INFO

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false  # 开启下划线转驼峰命名
    # 仅在开发环境开启日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete  # 逻辑删除的字段名
      logic-delete-value: 1 # 逻辑删除字段名和值
      logic-not-delete-value: 0 # 逻辑删除字段名和值

knife4j:
  enable: true
  openapi:
    title: 接口文档
    version: 1.0
    group:
      default:
        group-name: 梁懿豪
        api-rule: package
        api-rule-resources: com.lyh.picturerepobackend.controller
